apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghidra
  namespace: ghidra
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.100.10
    path: "/ghidra-pv"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ghidra
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghidra
  namespace: ghidra
  labels:
    app: ghidra
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ghidra
  volumeMode: Filesystem
