apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonus-p4
  namespace: bonus-p4
  labels:
    app: bonus-p4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bonus-p4
  template:
    metadata:
      labels:
        app: bonus-p4
    spec:
      containers:
      - name: bonus-p4
        image: ghcr.io/bonusplay/bonus.p4:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
      imagePullSecrets:
      - name: registry
---
apiVersion: v1
kind: Service
metadata:
  name: bonus-p4
  namespace: bonus-p4
spec:
  type: ClusterIP
  selector:
    app: bonus-p4
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bonus-p4
  namespace: bonus-p4
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-https@kubernetescrd,kube-system-p4net@kubernetescrd
spec:
  tls:
  - secretName: tls
    hosts:
    - "bonus.p4"
  rules:
  - host: bonus.p4
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: bonus-p4
            port:
              name: http
