# ---
# kind: NetworkPolicy
# apiVersion: networking.k8s.io/v1
# metadata:
#   name: public
# spec:
#   namespaceSelector:
#   - {key: network, operator: In, values: [public]}
#   ingress:
#   - from:
#     - podSelector:
#         matchLabels:
#           app: bookstore
# ---
# kind: NetworkPolicy
# apiVersion: networking.k8s.io/v1
# metadata:
#   name: policy
# spec:
#   ingress:
#   - from:
#     - ipBlock:
#         cidr: 192.168.0.0/24
# ---
# kind: NetworkPolicy
# apiVersion: networking.k8s.io/v1
# metadata:
#   name: policy
#   namespace: monitoring
# spec:
#   podSelector: {}
#   policyTypes:
#   - Ingress
#   ingress:
#   - from:
#     - ipBlock:
#         cidr: 198.18.0.0/16
