---
- name: find all files
  ansible.builtin.find:
    paths: "{{ role_path }}/files"
    patterns: "*.yaml"
    recurse: yes
  register: files
- name:
  kubernetes.core.k8s:
    src: "{{ item }}"
    state: present
  with_items: "{{ files.files | map(attribute='path') | replace(role_path + '/files/', '') }}"
