apiVersion: v1
kind: Service
metadata:
  name: calico-node-metrics
  namespace: kube-system
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9091'
spec:
  selector:
    k8s-app: calico-node
  type: ClusterIP
  ports:
  - port: 9091
    targetPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: calico-kube-controllers-metrics
  namespace: kube-system
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9094'
spec:
  selector:
    k8s-app: calico-kube-controllers
  type: ClusterIP
  ports:
  - port: 9094
    targetPort: 9094
