---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: prometheus-tls
  namespace: monitoring
data:
  tls.crt: "{{ prometheus.tls.crt | join('\n') | b64encode }}"
  tls.key: "{{ prometheus.tls.key | b64encode }}"
