apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: kutt
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12
        imagePullPolicy: IfNotPresent
        ports:
        - name: postgres
          containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: kutt-pv
          subPath: postgres
        env:
        - name: POSTGRES_USER
          value: "kutt"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: "kutt"
      volumes:
      - name: kutt-pv
        persistentVolumeClaim:
          claimName: kutt
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: kutt
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: postgres
