apiVersion: v1
kind: PersistentVolume
metadata:
  name: music
  namespace: lms
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 700Gi
  local:
    path: /mnt/drive_1/music
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - zion3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: music
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music
  namespace: lms
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 700Gi
  storageClassName: music
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lms
  namespace: lms
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  nfs:
    server: 192.168.100.10
    path: "/lms-pv"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: lms
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lms
  namespace: lms
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: lms
  volumeMode: Filesystem
