apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole
  namespace: pihole
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Mi
  nfs:
    server: 192.168.100.10
    path: "/pihole-pv"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pihole
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole
  namespace: pihole
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: pihole
  volumeMode: Filesystem
