apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kncyber
  namespace: cert-manager
spec:
  acme:
    email: acme@kncyber.pl
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-kncyber
    solvers:
      - dns01:
          cloudflare:
            email: cloudflare@bonusplay.pl
            apiKeySecretRef:
              name: cloudflare-api-token
              key: token
