apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak
  namespace: keycloak
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Mi
  nfs:
    server: 192.168.100.10
    path: "/keycloak-pv"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: keycloak
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: keycloak
  volumeMode: Filesystem
