apiVersion: v1
kind: PersistentVolume
metadata:
  name: warez
  namespace: warez
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  nfs:
    server: 192.168.0.20
    path: "/k8s/warez"
  mountOptions:
    - nfsvers=4.2,proto=tcp,port=2049
  persistentVolumeReclaimPolicy: Retain
  storageClassName: warez
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: warez
  namespace: warez
  labels:
    app: warez
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: warez
  volumeMode: Filesystem
