---
- name: copy sshd config
  ansible.builtin.copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
  register: result
- name: "{{ 'restart' if result.changed else 'start' }} sshd"
  ansible.builtin.service:
    name: sshd
    state: "{{ 'restarted' if result.changed else 'started' }}"
    enabled: yes
