---
- name: setup for alpine
  import_tasks: alpine.yaml
  when: ansible_facts['os_family']|lower == 'alpine'
- name: setup for debian
  import_tasks: debian.yaml
  when: ansible_facts['os_family']|lower == 'debian'
