apiVersion: v1
kind: ConfigMap
metadata:
  name: auth
  namespace: registry
data:
  htpasswd: |
    bonus:$2y$11$hX0vOQFwzJyS5DymqDh96uzt1Oa9l2im9tOhj4HHQ8KxHOl7Gw4ca
    cluster:$2y$11$io.OfoxwKtiDRbXwpUepOOtYUeuBe0k9.tPlch/veTe45jJ0XKJpq
    external:$2y$11$tFsBcCN8lWrZeTfQ75Y74.ddxlGhJMLndiGcV/tQfFwhcsC2OvSbq
