apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.100.10
    path: "/registry-pv"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: registry
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry
  namespace: registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: registry
  volumeMode: Filesystem
